### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by emporeso2** [sc0ttj/mdsh#55]
Hello,

is there a simple way to add , make an html template for the pages ?

Thanks.

**Comment by sc0ttj** [comment]
Not yet... What layout/HTML do you need? 

I am gonna add a grid layout at some point... And I still plan to separate out the HTML into template files, so *eventually* there will be a simple way of adding new templates/layouts.

**Comment by emporeso2** [comment]
Thanks it's exactly what i wanted to know : grid layout great , separate out the HTML to templates files.
If this is planned great wait to see.
Thanks again for your work.
